version: '3'
  
services:
        
    # brainchild/ltj
    tomcat:
        container_name: ltj${BRAINCHILD_LTJ_VERSION}
        image: brainchild/ltj:${BRAINCHILD_LTJ_VERSION}
        
        ports:
            - "${TOMCAT_LOCAL_PORT}:8080"
        
        # Enable the volumes to provide your local content
        #volumes:
            #- ${WEBAPPS_PATH}:/webapps
            #- ${CATALINA_CONF}:/etc/tomcat8
