version: '3'
  
services:
        
    # brainchild/pkgdrone
    tomcat:
        container_name: pkgdrone${BRAINCHILD_PKGDRONE_VERSION}
        image: brainchild/pkgdrone:${BRAINCHILD_PKGDRONE_VERSION}
        
        ports:
            - "${PKGDRONE_LOCAL_HTTP_PORT}:8080"
